@echo off
cd /d "%~dp0"
echo Cleaning old MAUI build files...
if exist bin rmdir /s /q bin
if exist obj rmdir /s /q obj
echo Restoring MAUI workloads...
dotnet workload restore
echo Restoring NuGet packages for Android target...
dotnet restore MediBook.csproj -p:TargetFramework=net10.0-android
echo Building Android Debug...
dotnet build MediBook.csproj -f net10.0-android -c Debug
pause
